"""
Django settings for vexation project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import environ
#root= environ.Path(__file__) -3
env = environ.Env(DEBUG=(bool, False),)
environ.Env.read_env()  # reading .env file
#SITE_ROOT = root()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
print("this is base_dir: " + str(BASE_DIR))
print("this is project_dir:" + str(PROJECT_DIR))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')


# Secret google recaptcha key (generated: 09.07.2018:
RECAPTCHA_PRIVATE_KEY = env('Recaptcha_private_key')
RECAPTCHA_PUBLIC_KEY = '6LcLD2MUAAAAAOudeAMOSayFdv-iTS8xCLrkLcuH'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django_extensions',            # muss ganz oben stehen. Starten mittels python manage.py runserver_plus
    'debug_toolbar',                   # funktioniert nicht ?!
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.admindocs',     # for django documentation in adminpanel
    'django.contrib.sites',         # for flatpages
    'django.contrib.flatpages',     # for flatpages

    'ckeditor',                     # editor for admin area -> blog:editing posts
    'ckeditor_uploader',            # for ckeditor
    'widget_tweaks',  # for contact-app
    'snowpenguin.django.recaptcha2',

    'django.contrib.sitemaps',



    'contact',
    'blog',
    'mixed',
    'gallery',



]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'vexation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),
                 ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
print("This is templates DIRS: " + str(os.path.join(BASE_DIR, 'templates')))

WSGI_APPLICATION = 'vexation.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

#TEMPORÄR ausgeschaltet um die PostgreSQL zu testen:

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql_psycopg2',
#        'NAME': 'vexation2',
#        'USER': 'styx',
#        'PASSWORD': 'vex8styx(48/11?!',
#        'HOST': 'localhost',
#        'PORT': '',
#    }
#}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'de-de'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)


# lt. RUBIO:
#STATIC_ROOT = '%s/static/' %(BASE_DIR)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

print("This is static_url: " + STATIC_URL)
print("This is staticfiles_dir: " + str(STATICFILES_DIRS))
print("This is media_url: " + MEDIA_URL)
print("This is static_root: " + str(MEDIA_ROOT))
# for contact-app: Specifying which email backend will be used:
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# implemetation for ckeditor:
CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'

CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_IMAGE_BACKEND = "pillow"


CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': None,
        "extraPlugins": 'codesnippet',
        "codeSnippet_theme": "monokai_sublime",

    },
}


# for flatpages
SITE_ID = 1


