# Generated by Django 2.0.7 on 2018-07-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='link_starter_image',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='link_starter_image',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
